use quote::quote;
use syn::DeriveInput;

pub fn derive_trivial_bridge(
    input: proc_macro::TokenStream,
) -> Result<proc_macro2::TokenStream, proc_macro2::TokenStream> {
    let input: DeriveInput = syn::parse(input).map_err(syn::Error::into_compile_error)?;

    let name = input.ident;
    let generics = &input.generics;

    let bridge_impl = quote! {
        /// This implementation is generated by the `TrivialBridge` derive macro, which is expected to be
        /// used only in the crate `opslang-ast`.
        impl #generics crate::Bridge for #name #generics {
            /// The `Full` type is the same as the original type.
            type Full = Self;

            /// The `Missing` type is `Infallible`, which means that it is never used.
            type Missing = ::std::convert::Infallible;

            #[inline(always)]
            /// Identity function.
            fn new(ok: Self::Full) -> Self {
                ok
            }

            /// Absurd function that is never called.
            fn new_missing(err: Self::Missing) -> Self {
                match err {}
            }
        }
    };

    Ok(bridge_impl)
}
