[package]
name = "opslang-ir-macro"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
proc-macro = true

[dependencies]
syn.workspace = true
proc-macro2.workspace = true
quote.workspace = true
synstructure.workspace = true
convert_case.workspace = true
opslang-visitor-macro-helper.workspace = true
