[package]
name = "opslang-typeck"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "ops file language type checker"

[dependencies]
opslang-ast = { path = "../opslang-ast", version = "0.4.0" }
opslang-ty = { path = "../opslang-ty", version = "0.4.0" }
opslang-ir = { path = "../opslang-ir", version = "0.4.0" }
opslang-ir-macro = { path = "../opslang-ir-macro", version = "0.4.0" }
opslang-visitor = { path = "../opslang-visitor", version = "0.4.0" }
anyhow = "1.0.98"
chrono = "0.4.41"

[dev-dependencies]
opslang-parser = { path = "../opslang-parser", version = "0.4.0" }
