[workspace]
resolver = "2"
members = [
    "opslang-ast",
    "opslang-parser",
]

[workspace.package]
version = "0.2.1"

[workspace.dependencies]
opslang-ast = { path = "opslang-ast" }
opslang-parser = { path = "opslang-parser" }
