use opslang_visitor::{TemplateVisit, Visitor, impl_template_visit_base_case};

/// A comprehensive visitor trait for all V1 AST types.
///
/// This trait provides `visit_*` and `super_*` methods for every V1 AST type,
/// allowing convenient traversal of the entire AST. Although it appears as an empty
/// trait definition due to the attribute macro, it actually contains generated methods
/// for all AST node types.
///
/// The trait includes method pairs like:
/// - `visit_program(&mut self, node: &Program<'cx>)` - visits a Program node
/// - `super_program(&mut self, node: &Program<'cx>)` - performs default traversal
/// - And similar pairs for every AST node type
///
/// The trait is automatically implemented for any type that implements the required
/// `Visitor` traits for individual AST types. The implementation delegates to the
/// individual `Visitor` trait implementations.
///
/// # Usage
///
/// ```ignore
/// struct MyVisitor;
/// v1_ast_visitor_impl! { impl for MyVisitor {
///     fn visit_program(&mut self, node: &Program<'_>) {
///         // Custom logic for visiting Program nodes
///     }
/// }}
///
/// // MyVisitor automatically implements AstVisitor
/// let mut visitor = MyVisitor;
/// visitor.visit_program(&program);  // Generated method available
/// ```
///
/// # Implementation Details
///
/// This trait is generated by the `declare_ast_visitor_trait` attribute macro,
/// which transforms the empty trait declaration into a full visitor trait with
/// methods for all AST types and provides a blanket implementation.
#[opslang_ast_macro::declare_ast_visitor_trait]
pub trait AstVisitor<'cx> {}

impl_template_visit_base_case!(
    super::DefaultTypeFamily,
    super::BytePos,
    super::Span,
    super::NumericKind,
);

/// Implement [`Visitor`] for [`Expr`], ignoring sealed field.
///
/// [`Expr`]: super::Expr
impl<'cx, F: super::TypeFamily<'cx>, V: ?Sized + Visitor<&'cx super::ExprKind<'cx, F>>>
    TemplateVisit<V> for super::Expr<'cx, F>
{
    fn super_visit(&self, visitor: &mut V) {
        visitor.visit(&self.0)
    }
}
