/// A helper trait to convert between different types of AST nodes.
pub trait Bridge {
    type Full;
    type Missing;

    fn new(ok: Self::Full) -> Self;
    fn new_missing(err: Self::Missing) -> Self;
}

impl<T, E> Bridge for Result<T, E> {
    type Full = T;
    type Missing = E;

    fn new(ok: Self::Full) -> Self {
        Ok(ok)
    }

    fn new_missing(err: Self::Missing) -> Self {
        Err(err)
    }
}

#[macro_export]
/// `#[derive(TrivialBridge)]` for possibly foreign types, including their reference types.
macro_rules! derive_trivial_bridge {
    ([for $($bound:tt)*] $ty:ty) => {
        /// This implementation is generated by the [`derive_trivial_bridge`] `macro_rules!`.
        impl<$($bound)*> Bridge for $ty {
            $crate::derive_trivial_bridge!(@content);
        }
    };
    ($ty:ty) => {
        /// This implementation is generated by the [`derive_trivial_bridge!`] `macro_rules!`.
        impl Bridge for $ty {
            $crate::derive_trivial_bridge!(@content);
        }
    };
    (@content) => {
        /// The `Full` type is the same as the original type.
        type Full = Self;

        /// The `Missing` type is `Infallible`, which means that it is never used.
        type Missing = std::convert::Infallible;

        #[inline(always)]
        /// Identity function.
        fn new(ok: Self::Full) -> Self {
            ok
        }

        /// Absurd function that is never called.
        fn new_missing(err: Self::Missing) -> Self {
            match err {}
        }
    }
}
