#[cfg(feature = "build-parol")]
fn build_parol() {
    use std::path::PathBuf;
    use std::process;

    use parol::{ParolErrorReporter, build::Builder};
    use parol_runtime::Report;

    #[allow(unused_mut, unused_variables)]
    let mut versions = Vec::new();

    {
        #[cfg(feature = "v1")]
        versions.push("v1");
    }

    let mut has_error = false;

    mod name {
        pub struct Path {
            pub path: &'static str,
        }
        impl AsRef<std::path::Path> for Path {
            fn as_ref(&self) -> &std::path::Path {
                self.path.as_ref()
            }
        }
        pub struct RustFile {
            pub path: &'static str,
            pub module: &'static str,
        }
        impl AsRef<std::path::Path> for RustFile {
            fn as_ref(&self) -> &std::path::Path {
                self.path.as_ref()
            }
        }

        pub const ACTION_MOD: &str = "parse";
        pub const USER_TYPE: &str = "Action";
        pub const GENERATED: &str = "generated";
        pub const GRAMMAR: Path = Path {
            path: "grammar.par",
        };
        pub const EXPANDED_GRAMMAR: Path = Path {
            path: "grammar-exp.par",
        };
        pub const PARSER: RustFile = RustFile {
            path: "parser.rs",
            module: "parser",
        };
        pub const TRAIT: RustFile = RustFile {
            path: "grammar_trait.rs",
            module: "grammar_trait",
        };
    }

    for v in versions {
        let input = {
            let mut path = PathBuf::from("src");
            path.push("version");
            path.push(v);
            path
        };
        let generated = {
            let mut path = PathBuf::from("src");
            path.push("version");
            path.push(v);
            path.push(name::GENERATED);
            path
        };
        std::fs::create_dir_all(&generated).unwrap();

        let grammar_file = input.join(name::GRAMMAR.path);
        if let Err(err) = Builder::with_explicit_output_dir(".")
            .grammar_file(&grammar_file)
            .expanded_grammar_output_file(generated.join(name::EXPANDED_GRAMMAR))
            .parser_output_file(generated.join(name::PARSER))
            .actions_output_file(generated.join(name::TRAIT))
            .user_trait_module_name(&format!("version::{v}::{path}", path = name::ACTION_MOD))
            .user_type_name(name::USER_TYPE)
            .trim_parse_tree()
            .generate_parser()
        {
            ParolErrorReporter::report_error(&err, &grammar_file).unwrap_or_default();
            has_error = true;
        }

        // Generate `generated.rs`
        let mut f = std::fs::File::create(generated.join("../generated.rs")).unwrap();
        {
            use name::*;
            use std::io::Write;
            writeln!(f, "// This file is generated by `build.rs`.").unwrap();
            writeln!(f, "// Do not edit it manually.").unwrap();
            writeln!(f).unwrap();
            for file in [TRAIT, PARSER] {
                let module_name = file.module;
                writeln!(f, "pub mod {module_name};").unwrap();
            }
        }
    }

    if has_error {
        process::exit(1);
    }

    // Generate `src/parol_macro.rs`
    let mut f = std::fs::File::create("src/parol_macro.rs").unwrap();
    {
        use name::*;
        use std::io::Write;
        writeln!(f, "// This file is generated by `build.rs`.").unwrap();
        writeln!(f, "// Do not edit it manually.").unwrap();
        writeln!(f).unwrap();
        let action = TRAIT.module;
        writeln!(
            f,
            r#"#[macro_export]
/// Redirect due to `actions_output_file` depending on `user_trait_module_name` in fact.
///
/// This macro is generated by `build.rs`.
macro_rules! redirect_parol {{
    () => {{
        mod {ACTION_MOD}_trait {{
            pub use super::{GENERATED}::{action}::{USER_TYPE}Auto;
        }}
    }};
}}"#
        )
        .unwrap();
    }
}

fn main() {
    #[cfg(feature = "build-parol")]
    build_parol();
}
