[package]
name = "opslang-parser"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "ops file language parser"

[features]
v0 = ["dep:peg"]
v1 = ["build-parol", "dep:typed-arena"]
build-parol = ["dep:parol", "dep:parol_runtime"]
default = ["v0", "v1"]

[dependencies]
opslang-ast.workspace = true
opslang-diag.workspace = true

peg.workspace = true
peg.optional = true
parol.workspace = true
parol.optional = true
parol_runtime.workspace = true
parol_runtime.optional = true
typed-arena.workspace = true
typed-arena.optional = true

thiserror.workspace = true
anyhow.workspace = true
chrono.workspace = true

[build-dependencies]
parol.workspace = true
parol.optional = true
parol_runtime.workspace = true
parol_runtime.optional = true
