[package]
name = "opslang-parser"
version.workspace = true
edition = "2021"
license = "MPL-2.0"
description = "ops file language parser"

[dependencies]
peg = "0.8.1"
thiserror = "1.0.48"
anyhow = "1.0.75"
opslang-ast = "0.2"
chrono = "0.4.33"
