// This file is generated by `build.rs`.
// Do not edit it manually.

#[macro_export]
/// Redirect due to `actions_output_file` depending on `user_trait_module_name` in fact.
///
/// This macro is generated by `build.rs`.
macro_rules! redirect_parol {
    () => {
        mod parse_trait {
            pub use super::generated::grammar_trait::ActionAuto;
        }
    };
}
