[package]
name = "opslang-ast"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "ops file language AST"

[features]
v0 = []
v1 = ["dep:typed-arena"]
default = ["v0", "v1"]

[dependencies]
opslang-ast-macros = { path = "../opslang-ast-macros", version = "0.4.0" }
opslang-visitor = { path = "../opslang-visitor", version = "0.4.0" }
opslang-visitor-macro = { path = "../opslang-visitor-macro", version = "0.4.0" }
typed-arena.version = "2.0.2"
typed-arena.optional = true

escape8259 = "0.5.3"
chrono = "0.4.33"
